# Generated by Django 6.0 on 2025-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='taken_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of quiz in minutes (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
